version: 2
jobs:  
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
          DIST: "/go/dist"
    steps:
      - checkout
      # (from: https://discuss.circleci.com/t/can-not-get-submodules-to-clone-properly/22120/2)
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build
          command: |
            set -xeu
            mkdir $DIST
            cd age
            # (from: https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04)
            platforms=("linux/amd64" "darwin/amd64" "windows/amd64" "linux/arm")
            for platform in "${platforms[@]}"
            do
                platform_split=(${platform//\// })
                export GOOS=${platform_split[0]}
                export GOARCH=${platform_split[1]}
                BUILD_PATH=age-$GOOS-$GOARCH
                mkdir $BUILD_PATH
                # Build
                # (base: https://github.com/FiloSottile/age/blob/31500bfa2f6a36d2958483fc54d6e3cc74154cbc/HomebrewFormula/age.rb#L17)
                go build -trimpath -o $BUILD_PATH filippo.io/age/cmd/...
                # Create .zip
                zip -r $DIST/$BUILD_PATH.zip $BUILD_PATH
                # Create .tar.gz
                tar zcvf $DIST/$BUILD_PATH.tar.gz $BUILD_PATH
            done
      - persist_to_workspace:
          root: /go/dist
          paths:
            - .

  github_release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: /go/dist
        - run:
            name: Publish Release on GitHub
            command: |
              VERSION=$CIRCLE_TAG
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /go/dist

workflows:
  version: 2
  build:
    jobs:
      - build :
          filters:
            tags:
              only: /.*/
      - github_release:
          requires:
            - build
          filters:
            tags:
              only: /.+/
            branches:
              ignore: /.*/
